import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase'
import { generateQRImage } from '@/lib/qr'

// FIX: HTML escape function to prevent XSS
function escapeHtml(text: string | null | undefined): string {
  if (!text) return ''
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
}

// POST /api/campaigns/[id]/qr/download - Generate PDF with all QR codes
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id: campaignId } = await params
  const supabase = createClient()

  // Auth check
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await req.json().catch(() => ({}))
  const { format = 'pdf', page_size = 'A4', layout = 'grid' } = body

  // Get campaign
  const { data: campaign } = await supabase
    .from('campaigns')
    .select('*')
    .eq('id', campaignId)
    .eq('brand_id', user.id)
    .single()

  if (!campaign) {
    return NextResponse.json({ error: 'Campaign not found' }, { status: 404 })
  }

  // Get all QR codes
  const { data: qrCodes } = await supabase
    .from('qr_codes')
    .select('*')
    .eq('campaign_id', campaignId)
    .eq('is_active', true)

  if (!qrCodes || qrCodes.length === 0) {
    return NextResponse.json({ error: 'No active QR codes found' }, { status: 404 })
  }

  // Generate HTML for PDF with XSS protection
  const qrHtml = qrCodes.map((qr, i) => `
    <div class="qr-item" style="
      width: ${layout === 'list' ? '100%' : '33%'};
      padding: 20px;
      text-align: center;
      page-break-inside: avoid;
    ">
      <img src="${escapeHtml(qr.qr_image_url) || generateQRImage(escapeHtml(qr.qr_slug))}"
           alt="QR Code" style="width: 200px; height: 200px;" />
      <p style="font-weight: bold; margin: 10px 0 5px;">${escapeHtml(qr.qr_label) || `QR ${i + 1}`}</p>
      ${qr.location_name ? `<p style="color: #666; font-size: 12px;">${escapeHtml(qr.location_name)}</p>` : ''}
      <p style="color: #999; font-size: 10px;">${escapeHtml(qr.qr_slug)}</p>
    </div>
  `).join('')

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #6366F1; }
        .header h1 { color: #6366F1; margin-bottom: 5px; }
        .header p { color: #666; }
        .qr-grid { display: flex; flex-wrap: wrap; justify-content: center; }
        .qr-item { border: 1px solid #eee; margin: 10px; padding: 15px; border-radius: 8px; }
        .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }
        @media print { .qr-item { border: 1px solid #ccc; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(campaign.name)}</h1>
        <p>${escapeHtml(campaign.description) || 'QR Code Pack'}</p>
        <p style="margin-top: 10px;">Total QR Codes: ${qrCodes.length}</p>
      </div>
      <div class="qr-grid">
        ${qrHtml}
      </div>
      <div class="footer">
        <p>Generated by AdsQr • ${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `

  if (format === 'html') {
    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
      }
    })
  }

  // For PDF, return HTML that can be printed
  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
    }
  })
}

// GET /api/campaigns/[id]/qr/download - Download QR codes
export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id: campaignId } = await params
  const supabase = createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get campaign and QR codes
  const { data: campaign } = await supabase
    .from('campaigns')
    .select('*')
    .eq('id', campaignId)
    .eq('brand_id', user.id)
    .single()

  if (!campaign) {
    return NextResponse.json({ error: 'Campaign not found' }, { status: 404 })
  }

  const { data: qrCodes } = await supabase
    .from('qr_codes')
    .select('qr_slug, qr_label, qr_image_url, location_name')
    .eq('campaign_id', campaignId)
    .eq('is_active', true)

  // Return data for client-side PDF generation
  return NextResponse.json({
    campaign: {
      id: campaign.id,
      name: campaign.name,
      description: campaign.description
    },
    qr_codes: qrCodes,
    download_url: `/api/campaigns/${campaignId}/qr/download`
  })
}
